### ISSUE TITLE
Digging Claws Client Crash

### ISSUE THREAD

**Issue by kristi71111** [Octo-Studios/rar-compat#4]
Latest version causes client side crash on using digging claws in combination with allthemodium items.

https://gist.github.com/kristi71111/3b4bc082df57158ad95089fe5b0ab8bb

Another separate crash reported on ATM discord:
https://mclo.gs/DWstX6m

**Comment by Temulla** [comment]
Hello. Thanks for the information. We are already solving this problem

**Comment by Temulla** [comment]
The fix is ​​already out and available for download: https://www.curseforge.com/minecraft/mc-mods/rar-compat/files/5989848
